trigger:
  - master

variables:
  - group: iot-to-cosmos-function

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - bash: 'sudo apt-get install azure-functions-core-tools'
  - task: Maven@3
    displayName: Maven-Package
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      codeCoverageTool: 'JaCoCo'
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      summaryFileLocation: '**/site/jacoco/jacoco.xml'
      goals: 'package'
  - bash: |
      mvn sonar:sonar \
        -Dsonar.projectKey=iceguard_iceguard-cosmos-functions \
        -Dsonar.organization=iceguard \
        -Dsonar.projectName=iceguard-cosmos-functions \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=$SONARCUBE_LOGIN_COSMOS_FUNCTIONS
  - task: CopyFiles@2
    displayName: 'Copy Files to: Artifact staging'
    inputs:
      SourceFolder: $(System.DefaultWorkingDirectory)
      Contents: '**/azure-functions/**'
      TargetFolder: $(Build.ArtifactStagingDirectory)
  - task: ArchiveFiles@2
    displayName: 'Archive $(Build.ArtifactStagingDirectory)/target/azure-functions/$(functionAppMvnTargetFolder)'
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/target/azure-functions/$(functionAppMvnTargetFolder)'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      includeRootFolder: false
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      artifactName: 'cosmos-functions-artifact'